all:
  browse:
    # How many to display per page
    per_page:           12

  gravatar:
    default_size:       48
    default_rating:     G
    default_image:      gravatar-48.png
    cache_dir_name:     avatars
    cache_expiration:   3 days
