prod:
  git:
    command:            /opt/local/bin/git #make sure it's correct
  
  twitter:
    consumer_key:       #fill
    consumer_secret:    #fill
    
dev:
  git:
    command:            /opt/local/bin/git #make sure it's correct
  
  twitter:
    consumer_key:       #fill for your local environment
    consumer_secret:    #fill for your local environment

# default values
all:
  git:
    storage_path:       <?php echo sfConfig::get('sf_root_dir') ?>/git/
  
  plugin:
    # Dev loose mode lessens the checks for submission in dev environment
    dev_loose_mode:     on
  
  browse:
    # How many to display per page
    per_page:           10    
  
  gravatar:
    default_size:       48
    default_rating:     G
    default_image:      gravatar-48.png
    cache_dir_name:     avatars
    cache_expiration:   3 days