default:
  http_metas:
    content-type: text/html

  metas:
    title:        MooTools Forge
    description:  MooTools Plugins directory
    language:     en
    robots:       index, follow
    viewport:     width=device-width, user-scalable=no

  stylesheets:
    - screen.css
    - http://fonts.googleapis.com/css?family=Roboto:200,300,400,600,700,200italic,300italic,400italic,600italic,700italic
    - http://fonts.googleapis.com/css?family=Source+Code+Pro:200,300,400,500,600,700
    - //<?php echo sfContext::getInstance()->getRequest()->getHost(); ?>/css/style.css
    - pluginskit.css

  javascripts:    [mootools-1.2.2-core+more.js, lighter.js, passshark.js, pluginskit.js, fancyzoom.js, fancyzoom.html.js]

  has_layout:     true
  layout:         layout
