default:
  http_metas:
    content-type: text/html

  metas:
    title:        PluginsKit
    description:  Plugins directory
    language:     en
    robots:       index, follow

  stylesheets:    [screen.css, print.css: {media: print}, pluginskit.css]

  javascripts:    [mootools-1.2.2-core+more.js, lighter.js, pluginskit.js, fancyzoom.js, fancyzoom.html.js]

  has_layout:     on
  layout:         layout
