all:
  
  title_prefix:         MooTools Plugins |
  
  webmaster:
    email:              forge@mootools.net
    
  screenshots:     
    path:               screenshots
    width:              120
    height:             85
    primarywidth:       185
    primaryheight:      78
    
  sfImageTransformPlugin:
    default_adapter: GD
    mime_type:
      auto_detect: true
      library: GD_MIME_Type    